//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.04.04 at 08:02:09 AM BST
//

package uk.gov.ons.census.fwmtadapter.model.dto.field;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import lombok.Data;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "ActionCancel",
    propOrder = {"caseId", "addressType"})
@Data
public class ActionCancel extends Action {
  protected String caseId;
  protected String addressType;
}
