spring:
  datasource:
    url: jdbc:postgresql://localhost:6432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    initialization-mode: always
    hikari:
      maximumPoolSize: 50

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: fwmtadapter
        jdbc:
          lob:
            non_contextual_creation: true

  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 6672
    virtualhost: /

queueconfig:
  action-field-queue: Action.Field
  outbound-exchange: adapter-outbound-exchange
  adapter-outbound-queue: RM.Field
  consumers: 50

healthcheck:
  frequency: 1000 #milliseconds
  filename: /tmp/fwmt-adapter-healthy
