spring:
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 6672
    virtualhost: /

queueconfig:
  action-field-queue: Action.Field
  outbound-exchange: adapter-outbound-exchange
  adapter-outbound-queue: RM.Field
  receipt-queue: FieldWorkAdapter.Responses
  consumers: 50

healthcheck:
  frequency: 1000 #milliseconds
  filename: /tmp/fwmt-adapter-healthy

case-api:
  host: "http://caseapi"
  port: 8161
