spring:
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 6672
    virtualhost: /

queueconfig:
  action-field-queue: Action.Field
  outbound-exchange: adapter-outbound-exchange
  receipt-queue: FieldWorkAdapter.Responses
  case-event-exchange: events
  refusal-queue: FieldworkAdapter.Refusals
  invalid-address-inbound-queue: FieldworkAdapter.invalidAddress
  consumers: 50

healthcheck:
  frequency: 1000 #milliseconds
  filename: /tmp/fwmt-adapter-healthy

caseapi:
  host: case-api
  port: 80

messagelogging:
  logstacktraces: false
