spring:
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 6672
    virtualhost: /

queueconfig:
  action-field-queue: Action.Field
  outbound-exchange: adapter-outbound-exchange
  refusal-queue: FieldworkAdapter.Refusals
  invalid-address-inbound-queue: FieldworkAdapter.invalidAddress
  uac-updated-queue: FieldworkAdapter.uacUpdated
  consumers: 50
  retry-attempts: 3
  retry-delay: 1000 #milliseconds
  retry-exchange: delayedRedeliveryExchange
  quarantine-exchange: quarantineExchange

healthcheck:
  frequency: 1000 #milliseconds
  filename: /tmp/fwmt-adapter-healthy

caseapi:
  host: localhost
  port: 8161

exceptionmanager:
  connection:
    scheme: http
    host: localhost
    port: 8666

messagelogging:
  logstacktraces: false
