spring:
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 6672
    virtualhost: /

queueconfig:
  action-field-queue: Action.Field
  outbound-exchange: adapter-outbound-exchange
  adapter-outbound-queue: RM.Field
  receipt-queue: FieldWorkAdapter.Responses
  receipt-routing-key: event.response.receipt
  case-event-exchange: events
  refusal-queue: FieldworkAdapter.Refusals
  refusal-routing-key: event.respondent.refusal
  invalid-address-routing-key: event.case.address.update
  invalid-address-inbound-queue: FieldworkAdapter.invalidAddress
  consumers: 50

healthcheck:
  frequency: 1000 #milliseconds
  filename: /tmp/fwmt-adapter-healthy

caseapi:
  host: case-api
  port: 80
