package uk.gov.ons.census.fwmtadapter.model.dto;

public enum EventType {
  CASE_CREATED,
  CASE_UPDATED,
  UAC_UPDATED,
  PRINT_CASE_SELECTED,
  REFUSAL_RECEIVED,
  RESPONSE_RECEIVED,
  ADDRESS_NOT_VALID,
  ADDRESS_MODIFIED,
  ADDRESS_TYPE_CHANGED,
  NEW_ADDRESS_REPORTED
}
